version: '3'
services:
    web:
        build:
            context: ./Presentation/TGS.Cartorio.Presentation.Angular
            dockerfile: Dockerfile.dev
        ports: 
            - "4200:4200"
        volumes: 
            - /app/node_modules
            - C:\\git\\Cartorio\\Presentation\\TGS.Cartorio.Presentation.Angular:/app
        