#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 16000

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["TGS.Correios.API/TGS.Correios.API.csproj", "TGS.Correios.API/"]
RUN dotnet restore "TGS.Correios.API/TGS.Correios.API.csproj"
COPY . .
WORKDIR "/src/TGS.Correios.API"
RUN dotnet build "TGS.Correios.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TGS.Correios.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish/apicorreios .
ENTRYPOINT ["dotnet", "TGS.Correios.API.dll"]